modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "uneffectual"
version = "${file.jarVersion}"
displayName = "Uneffectual"
updateJSONURL = "https://raw.github.com/cofh/version/main/uneffectual/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH, Darkosto"
authors = "King Lemming"
description = '''
Don't want effect icons? Remove them. Configurable on a per-effect basis.
'''
[[dependencies.uneffectual]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.uneffectual]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"
